version: '3.8'

services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: mysql:8.0
    env_file:
      - ".env"
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql

volumes:
  db: { }
