version: '3.8'

services:
  db:
    # ВНИМАТЕЛЬНО! ВОТ ЭТО НАЗВАНИЕ СЕРВИСА - db - ДОЛЖНО БЫТЬ УКАЗАНО В БОТЕ КАК host В ПОДКЛЮЧЕНИИ К БАЗЕ ИЗ БОТА
    # ТО ЕСТЬ НЕ АЙПИШНИК И НЕ ЛОКАЛХОСТ, А db
    # DB_HOST: db
    container_name: database
    image: mysql:8.0
    env_file:
       - ".env"
    restart: always
    ports:
      - 3306:3306
    networks:
      - botnet
    volumes:
      - ./data:/var/lib/mysql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnet:
    driver: bridge